main-최근게시물 api 연동
steamed-potatoes/potato-front pull request #50
Opened 2021-05-01 01:33 UTC by JeongYunMi

먼저 올렸는데 확인부탁드립니다..!

2021-05-01 17:30 UTC, seungh0 requested changes

2021-05-01 17:30 UTC, seungh0 commented on src/apis/sendApi.js
> +      'https://api.pmarket.space/api/v2/organization/board/list?size=5'
1. 차후에 서버 URL이 바뀐다거나 하면 요렇게 코드에 직접 입력하면 나중에 모든 API를 일일이 바꿔야 합니다!
그래서 보통 .env (환경변수) 파일에 baseUrl을 저장하구 사용합니다! (common.js, sendApi.js 참고 하시면 좋을거 같아요)

2. 위에 11번줄 처럼 
`await api.send('/api/v2/....') `하는것이 좋아보여요!

3. 참고로 .env 파일이 없으시면 노션 -> 시크릿? 에 .env 있습니다! (비밀정보라 .gitignore 처리 되어 있어서)

2021-05-04 19:33 UTC, seungh0 requested changes

2021-05-04 19:33 UTC, seungh0 commented on src/apis/sendApi.js
> +    );
차후에 서버 URL이 바뀐다거나 하면 요렇게 코드에 직접 입력하면 나중에 모든 API를 일일이 바꿔야 합니다!
그래서 보통 .env (환경변수) 파일에 baseUrl을 저장하구 사용합니다! (common.js, sendApi.js 참고 하시면 좋을거 같아요)

.env파일은 노션에 시크릿~ 가보시면 있을거에요

2021-05-04 19:33 UTC, seungh0 commented on src/apis/common.js
> +  },
따로 만드신 이유가 있을까요..?

위에 send()를 사용하는것이 좋아보여요~
sendApi 파일의 signUpMember() 참고하시면 좋을거 같습니다!!
sn

2021-05-05 11:12 UTC, artvelop commented on src/apis/sendApi.js
> +    );
굳굳

2021-05-05 11:12 UTC, artvelop commented on src/page/main/NewBoardView.jsx
> +        swal(`${e}`);
e.message로 바꿔주세요

2021-05-05 11:13 UTC, artvelop commented on src/apis/common.js
> +  },
sendApi랑 common의 관계 확인해주세요

2021-05-07 09:27 UTC, artvelop commented on src/page/main/NewBoardView.jsx
> +        swal(`${e}`);
e.reponse.data.message로 바꿔주세요

2021-05-08 05:36 UTC, merged