회원가입 페이지 API연동
steamed-potatoes/potato-front pull request #51
Opened 2021-05-01 12:22 UTC by minho0315

학과는 select로 바꿔서 값 받아왔고
값은 submit 할 때 localStorage에 저장하고 main 페이지로 넘어가게 했는데 확인 부탁드려요

2021-05-01 17:25 UTC, seungh0 requested changes
저는 디자인 이런거 제외하고 기능? 적으로만 리뷰했습니다~

2021-05-01 17:25 UTC, seungh0 commented on src/apis/common.js
> +  },
따로 send2를 만든 이유가 있으신가요...?

2021-05-01 17:25 UTC, seungh0 commented on src/page/signUp/SignUpBody.jsx
> +  localStorageService.delete('signUpData');
로컬스토리지에 회원가입 API 호출 후 반환되는 토큰을 보관하고 있어야 할거 같습니다!
(서버로 부터 받아온 토큰(인증서)를 클라이언트 보관소 (LocalStorage)에 보관한다고 생각하면 좋을거 같아요!

2021-05-01 17:25 UTC, seungh0 commented on src/apis/sendApi.js
> +    return await api.send2('https://api.pmarket.space/api/v1/major/list',req, 'get');
1. 차후에 서버 URL이 바뀐다거나 하면 요렇게 코드에 직접 입력하면 나중에 모든 API를 일일이 바꿔야 합니다!
그래서 보통 .env (환경변수) 파일에 baseUrl을 저장하구 사용합니다! (common.js, sendApi.js 참고 하시면 좋을거 같아요)

2. 참고로 네이밍은 "전공을 조회한다" 느낌을 살려서 getMajors or retrieveMajors 이런식으로 짓는것이 좋습니다.

2021-05-01 17:25 UTC, seungh0 commented on src/page/signUp/SignUpBody.jsx
> +  localStorageService.delete('signUpData');
### Flow
플로우가 이렇게 될 거 같아요!
1.  https://github.com/steamed-potatoes/potato-front/blob/develop/src/store/modules/user.js 에 있는 값들을 이용해서 
이메일, 이름, 프로필 사진, 전공을 회원가입 API 호출해서

2. 호출 후 받아온 토큰을 로컬스토리지에 저장한다

3. /Main으로 이동시킨다.

2021-05-01 17:25 UTC, seungh0 commented on src/page/google/GoogleCallback.jsx
> +      // console.log(code);
console.log()는 커밋하기 전에 다 지우는 것이 좋아요~

2021-05-01 17:33 UTC, seungh0 commented on src/apis/sendApi.js
> +    return await api.send2('https://api.pmarket.space/api/v1/major/list',req, 'get');
.env 파일은 노션 -> 시크릿? 에 있을거에요

2021-05-03 02:09 UTC, minho0315 commented on src/apis/common.js
> +  },
오 .env baseUrl을 몰라서 연동 테스트하는데 연결이 안되서 따로 만들었어요!! 수정할께요! 감사합니다

2021-05-03 02:09 UTC, minho0315 commented on src/page/signUp/SignUpBody.jsx
> +  localStorageService.delete('signUpData');
오 제일 궁금했던거에요 수정할께요!

2021-05-03 02:09 UTC, minho0315 commented on src/apis/sendApi.js
> +    return await api.send2('https://api.pmarket.space/api/v1/major/list',req, 'get');
넵넵!!

2021-05-03 02:10 UTC, minho0315 commented on src/page/google/GoogleCallback.jsx
> +      // console.log(code);
아 넵넵 수정하고 commit하겠습니다!

2021-05-04 16:38 UTC, minho0315 commented
send2 지우고 console.log 도 지웠습니다!
말씀해주신 flow 따라서 코드 수정해봤습니다. 
그 궁금한점이 닉네임은 어디다 저장해야할까요?? 
아 그리고 notion에 시크릿에 .env baseUrl 이 프론트쪽이 살짝 잘못되어있는것 같아서 수정했어요

2021-05-04 17:03 UTC, seungh0 commented
프론트 잘 모르지만...... 지금 생각나는 방법은

**1. 최초로 메인 화면을 랜더링 할때, 서버로부터 회원정보를 가져오는 API를 요청해서 회원정보를 가져와서,** 

cf) 이때 로컬스토리지에 보관해둔 토큰을 서버로 Authorization 헤더에 포함해서 넘겨줘야 합니다.
```
GET https://api.pmarket.space/api/v1/member

Authorization: Bearer <토큰 값>
```


**2. 그리고 받아온 회원 정보를 상태관리 라이브러리에 넣고,필요할때 상태 정보를 가져와서 화면에 뿌려줄거 같아요!**

(대신 만약 마이페이지에서 회원 정보가 변경되면, 그 상태 정보에도 변경해줘야겠죠...!)

2021-05-04 17:08 UTC, seungh0 commented on src/page/signUp/SignUpBody.jsx
> +          <Input name="classNumber" onChange={handleChange} />
이름, 학과도 그렇고
```
value ={classNumber}
```
가 있어야 되지 않나여??

2021-05-04 17:08 UTC, seungh0 commented on src/page/signUp/SignUpBody.jsx
> +          <Input name="nickname" onChange={handleChange} />
닉네임 변경시(onChange) 리덕스에 관리하는 상태값(name) 을 변경해주는 것이..?

2021-05-05 02:38 UTC, minho0315 commented on src/page/signUp/SignUpBody.jsx
> +          <Input name="classNumber" onChange={handleChange} />
아 넵넵

2021-05-05 02:39 UTC, minho0315 commented on src/page/signUp/SignUpBody.jsx
> +          <Input name="nickname" onChange={handleChange} />
아 넵넵

2021-05-05 06:14 UTC, minho0315 commented
value 추가하고 nickname을 상태값(name) 변경 적용했어요!

2021-05-05 06:55 UTC, seungh0 commented
좋은거 같아욤!! 머지해주세염~ 
그 전에 CI가 실패하는데
![image](https://user-images.githubusercontent.com/48153675/117106096-39318100-adba-11eb-8b2e-0c359baa82fa.png)

요것만 한번 확인해주세요~

2021-05-05 07:51 UTC, minho0315 commented
음 Signup.jsx를 SignUp.jsx로 바꿨었는데 그것 때문인가요? 다시 바꿨어요!

2021-05-05 07:56 UTC, merged