내 프로필put, 속한 그룹리스트 get API 생성하고 가져옴
steamed-potatoes/potato-front pull request #68
Opened 2021-05-11 14:43 UTC by bigyou98

내가 속한 그룹 1로 뜸, length로 뜨는 것인가..

2021-05-12 01:10 UTC, seungh0 requested changes

2021-05-12 01:10 UTC, seungh0 commented on src/page/myPage/MyPage.jsx
> +  // 이렇게 안하면 버튼 클릭 이벤트에서 state를 수정하기 힘들 것 같음
주석 왠만하면 남겨놓지 않는게 좋아요
(정말 필요한 경우 최소한으로)

2021-05-12 01:10 UTC, seungh0 commented on src/page/myPage/TextBox.jsx
> +        console.log(groupListData);
이런 콘솔 확인도 커밋하기 전에 다 지워주세요

2021-05-12 01:10 UTC, seungh0 commented on src/page/myPage/TextBox.jsx
> +        const GL = groupListData.data;
```
setGroupNameList(groupListData.data);
```
로 하면 더 깔끔.

2021-05-12 01:10 UTC, seungh0 commented on src/page/myPage/TextBox.jsx
> +        }
이거 왜 넣은건지??...

2021-05-12 01:10 UTC, seungh0 commented on src/page/myPage/TextBox.jsx
> +        alert(error);
alert(error.response.data.message);

2021-05-12 01:10 UTC, seungh0 commented on src/page/myPage/TextBox.jsx
>  const PTag = styled.p`
스타일 컴포넌트 정의한건 위에다가 모아두는게,.

2021-05-12 04:50 UTC, artvelop commented on src/page/myPage/MyPage.jsx
> +  // 이렇게 안하면 버튼 클릭 이벤트에서 state를 수정하기 힘들 것 같음
주석은 코드를 이해하기 힘들꺼같을 때만 남겨주세요

2021-05-12 04:51 UTC, artvelop commented on src/page/myPage/TextBox.jsx
> +  // const [myGroup, setMyGroup] = useState('디자인-온');
이거 제거부탁드립니다

2021-05-12 05:14 UTC, artvelop commented
개발끝나시면 테스트 한 번 꼼꼼하게 해주세요
코드 정리도 한번 해주면 좋을꺼같아요

2021-05-12 08:47 UTC, bigyou98 commented on src/page/myPage/TextBox.jsx
> +        }
이거 아직 아무것도 그룹가입안했을때 그냥 방어코드? 느낌

2021-05-15 12:22 UTC, artvelop commented on src/page/myPage/TextBox.jsx
> +        }
그건 처리할려면 태그부분에서 처리해야죸ㅋㅋㅋㅋ
지워주십셔

2021-05-21 06:39 UTC, closed without merging